main/urls.py
from django.urls import include, path

from .views import scholarship, staffs, students 


urlpatterns = [
    path('', scholarship.home ,name = 'home' ),
    path('students/', include((
            [
                path('', students.ViewScholarships.as_view(), name='view_scholarships'),
                path('apply/<int:pk>/', students.SubmitScholarshipApplication, name='apply_scholarship'),
                path('description/<int:pk>/', students.ShowDescription, name='scholarship_description'),
                path('applied_scholarships/', students.ViewSubmittedScholarships.as_view(), name='applied_scholarship'),
            ], 'sms'
    ), namespace='students'
    ))
]

sms/urls.py
from django.contrib import admin
from django.urls import path, include

from main.views import scholarship, students

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('', include('main.urls')),
    path('teams/', scholarship.team),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/signup/student/', students.StudentSignUpView.as_view(), name='student_signup'),
]

main/models.py
from django.db import models


from django.db import models
from django.contrib.auth.models import AbstractUser
from ckeditor.fields import RichTextField

# Create your models here.

class User(AbstractUser):
    is_student = models.BooleanField(default=False)
    is_staff = models.BooleanField(default=False)


class Scholarship(models.Model):
    scholarship_type = models.CharField(max_length=255)
    application_open_date = models.DateTimeField()
    application_close_date = models.DateTimeField()
    scholarship_field = RichTextField()
    money = models.IntegerField()
    number_of_opening = models.IntegerField()
    scholarship_status = models.TextField()

    def __str__(self):
        return self.scholarship_type 

class Application(models.Model):
    scholarship_type = models.ForeignKey(Scholarship, null=True, blank=True, on_delete=models.SET_NULL)
    approved = models.BooleanField(default=False)
    reviewed = models.BooleanField(default=False)
    name = models.CharField(max_length=300)
    permanent_mailing_address = models.TextField()
    phone_number = models.CharField(max_length=255)
    birth_date = models.DateField()
    high_school_name = models.TextField()
    high_school_diploma_date = models.DateField()
    high_school_GPA = models.FloatField()
    university_choice = models.TextField()
    major_field_of_study = models.TextField()
    enrolled_to_university = models.BooleanField()
    essay = models.FileField(upload_to="essays/")
    documents = models.FileField(upload_to="documents/")

    def __str__(self):
        if self.scholarship_type :
            return  self.scholarship_type.scholarship_type +  " -->  " + self.name
        else:
            return self.name


class Student(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE,primary_key=True)
    applications = models.ManyToManyField(Application)
    #scholarships =

main/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.db import transaction
from django.forms.utils import ValidationError

from main.models import (Application, User , Student)


class StudentSignUpForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User

    @transaction.atomic
    def save(self ):
        user = super().save(commit=False)
        user.is_student = True
        user.save()
        student = Student.objects.create(user=user) 
        return user

class ApplicationForm(forms.ModelForm):
    class Meta:
        model = Application
        exclude = ('reviewed','approved', 'scholarship_type',)
    
    def save(self):
        print(self.cleaned_data)
        application = Application.objects.create(**self.cleaned_data) 
        return application
    

main/views/scholarship.py
from django.shortcuts import redirect, render
from django.views.generic import TemplateView


class SignUpView(TemplateView):
    template_name = 'registration/signup.html'


def home(request):
    if request.user.is_authenticated:
        if request.user.is_staff:
            return redirect('staffs:view_scholarship_submission')
        else:
            return redirect('students:view_scholarships')
    return render(request, 'main/home.html')

def team(request):
    return render(request, 'team.html')

main/views/staffs.py
from django.contrib import messages
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required
from django.db import transaction
from django.db.models import Count
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import CreateView, ListView, UpdateView

from ..decorators import staff_required
from ..forms import ApplicationForm, StudentSignUpForm 
from ..models import Application 

@method_decorator([login_required, staff_required], name='dispatch')
class ViewScholarshipSubmission(ListView):
    model = Application
    ordering = ('name', )
    context_object_name = "Application"
    template_name = 'main/staffs/application_list.html'

    def get_queryset(self):
        queryset = Application.objects.all()
        return queryset
    

main/views/students.py
from re import S
from django.contrib import messages
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required
from django.db import transaction
from django.db.models import Count
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import CreateView, ListView, UpdateView

from ..decorators import student_required
from ..forms import ApplicationForm,StudentSignUpForm
from ..models import Scholarship, Student, Application, User

class StudentSignUpView(CreateView):
    model = User
    form_class = StudentSignUpForm 
    template_name= 'registration/signup_form.html'

    def get_context_data(self, **kwargs):
        kwargs['user_type'] ='student'
        return super().get_context_data(**kwargs)
    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return redirect('students:view_scholarships')

class ViewScholarships(ListView):
    model = Scholarship
    context_object_name = 'Scholarship'
    template_name = 'main/students/scholarships_list.html'

    def get_queryset(self):
        queryset = Scholarship.objects.all()
        return queryset

def ShowDescription(request, pk):
    scholarship = get_object_or_404(Scholarship, pk=pk)
    return render(request,'main/students/scholarship_description.html', {'scholarship': scholarship})

def SubmitScholarshipApplication(request, pk):
    scholarship = get_object_or_404(Scholarship, pk=pk)
    student = request.user.student
    if request.method == 'POST':
        form = ApplicationForm(request.POST,request.FILES)
        print(form.data)
        print(form.errors)
        if form.is_valid():
            form.cleaned_data['scholarship_type'] = scholarship
            student.applications.add(form.save())
        else:
            return render(request, 'main/students/application_form.html', {'scholarship': scholarship, 'form': form, 'errors': form.errors})


        return redirect('students:view_scholarships')
    else: 
        form = ApplicationForm(initial={'scholarship_type': scholarship})
    

    return render(request, 'main/students/application_form.html', {'scholarship': scholarship, 'form': form})

class ViewSubmittedScholarships(ListView):
    model = Application
    context_object_name = 'Applications'
    template_name = 'main/students/submitted_application.html'


    def get_queryset(self):
        data = self.request.user
        student = Student.objects.get(user=data)
        return student.applications.all()

main/templates/main/home.html
{% extends 'base.html' %}

{% block content %}
  <h2>Welcome to Scholarship management System! <span class="icon-emo-happy"></span></h2>
  <p class="lead">
    If you already have an account, go ahead and <a href="{% url 'login' %}">log in</a>. If you want to apply for scholarship, start   
    by creating a <a href="{% url 'student_signup' %}">student account</a>.
  </p>
  <hr>
  <h3>What's this about?</h3>
  <p>
    This application allows you to apply for various scholarship. Staffs will review your application and if we like your application we will send you email notification.
  </p>
  <style>
    .reason-flex {
      display:flex;
      justify-content:space-between ;
      width:100%;
    }
    .reason-flex .item {
      width:33%;
      text-align: center;
    }
    .reason-flex .item img{
      width:100px; 
    }
  </style>
  <div class="scholarship">
      <p class="center">Why Scholarship Management System?</p>
      <div class="reason-flex">
        <div class="item">
          <img src="https://img.icons8.com/external-flaticons-lineal-color-flat-icons/344/external-recommendation-literature-flaticons-lineal-color-flat-icons.png"/>
          <div>Get matched with scholarship you want</div>
        </div>
        <div class="item">
          <img src="https://img.icons8.com/nolan/344/certificate.png"/>
          <div>Browse through various scholarships</div>
        </div>
        <div class="item">
          <img src="https://img.icons8.com/plasticine/344/money.png"/>
          <div>Ease your loans</div>
        </div>

      </div>
  </div>
{% endblock %}

main/templates/main/staffs/application_list.html
{% extends 'base.html' %}

{% block content %}
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item active" aria-current="page">Submitted Applications</li>
    </ol>
  </nav>
  <h2 class="mb-3">Submitted Applications</h2>
  <div class="card">
    <table class="table mb-0">
      <thead>
        <tr>
          <th>Application</th>
          <th>Reviewed</th>
          <th>Approved</th>
          <th>View Application</th>
        </tr>
      </thead>
      <tbody>
        {% for application in Application %}
          <tr>
            <td class="align-middle"><a href="{% url 'staff:view_submission' application.id %}">{{ application.name }}</a></td>
            <td class="align-middle">{{ application.reviewed }}</td>
            <td class="align-middle">{{ application.approved }}</td>
            <td class="align-middle"><a href="{% url 'staff:view_submission' application.id %}">View Submission</a></td>
          </tr>
        {% empty %}
          <tr>
            <td class="bg-light text-center font-italic" colspan="5">There are no submitted applications yet</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
{% endblock %}

main/templates/main/students/application_form.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content %}

  <h2 class="mb-3">Submit for {{ scholarship.scholarship_type }}</h2>
  {% if errors %}
    {{errors | safe }}  
  {% endif %}
  <form method="post" enctype="multipart/form-data" novalidate>
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="btn btn-success">Save changes</button>
    <a href="{% url 'students:view_scholarships' %}" class="btn btn-outline-secondary">Nevermind</a>
  </form>
{% endblock %}

main/templates/main/students/scholarship_description.html
{% extends 'base.html' %}

{% block content %}
<h1>{{ scholarship.scholarship_type }}</h1>

<br/>
<br/>
<style>
    .time {
        font-size: 20px;
        background: #3d3d;
        padding: 20px;
        border-radius: 20px;
    }
    .money {
        background: #2d2d30;
        color: white;
        margin-top: 30px;
        margin-bottom: 30px;
        font-size: 30px;
        text-align: center;
        border-radius: 20px;

    }
</style>
<div>
    <div class="time">
        <p>Application Closing Date : {{ scholarship.application_open_date }}</p>
        <p>Application Opening Date : {{ scholarship.application_close_date }} </p>
    </div>
    <div class = "money">
        $ {{scholarship.money}}
    </div>

    <div>
        {{scholarship.scholarship_field | safe}}
    </div>
</div>
{% endblock %}

main/templates/main/students/scholarships_list.html
{% extends 'base.html' %}

{% block content %}
  <div>
     <a href="{% url 'students:applied_scholarship' %}"><h4>view your application status</h4></a>

     <hr>
  </div>
  <div class="card">
    <table class="table mb-0">
      <thead>
        <tr>
          <th>Scholarship</th>
          <th>Open Date</th>
          <th>Close Date</th>
          <th>Grant</th>
          <th>Apply</th>
        </tr>
      </thead>
      <tbody>
        {% for scholarship in Scholarship %}
          <tr>
            <td><a href="{% url 'students:scholarship_description' scholarship.id %}">{{ scholarship.scholarship_type }}</a></td>
            <td>{{ scholarship.application_open_date}} </td>
            <td>{{ scholarship.application_close_date }}</td>
            <td>${{ scholarship.money}}</td>
            <td><a href="{% url 'students:apply_scholarship' scholarship.id %}">Apply</a></td>
          </tr>
        {% empty %}
          <tr>
            <td class="bg-light text-center font-italic" colspan="3">No scholarships open yet </td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
{% endblock %}

main/templates/main/students/submitted_application.html
{% extends 'base.html' %}

{% block content %}
  <div>
     <a href="#"><h4>Submitted Applications</h4></a>

     <hr>
  </div>
  <div class="card">
    <table class="table mb-0">
      <thead>
        <tr>
          <th>Scholarship</th>
          <th>Reviewed</th>
          <th>Approved</th>
        </tr>
      </thead>
      <tbody>
        {% for application in Applications %}
          <tr>
            <td>{{ application.scholarship_type }}</td>
            <td><input type="checkbox" value ="{{application.reviewed}}"/> </td>
            <td><input type="checkbox" value ="{{application.approved}}"/> </td>
          </tr>
        {% empty %}
          <tr>
            <td class="bg-light text-center font-italic" colspan="3">No scholarships applied yet</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
{% endblock %}

templates/base.html
{% load static %}<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{% block title %}Scholarship Management System{% endblock %}</title>
    <link rel="icon" href="{% static 'img/favicon.png' %}">
    <link href="https://fonts.googleapis.com/css?family=Clicker+Script" rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'vendor/fontello-2f186091/css/fontello.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/app.css' %}">
    {% if user.is_authenticated and user.is_staff %}
      <link rel="stylesheet" type="text/css" href="{% static 'css/teachers.css' %}">
    {% else %}
      <link rel="stylesheet" type="text/css" href="{% static 'css/students.css' %}">
    {% endif %}
  </head>
  <body>
    <div class="container my-4">
      <div class="row justify-content-center">
        <div class="col-md-10 col-sm-12">
          <div class="row">
            <div class="col-6">
              <h1 class="logo">
                <a href="{% url 'home' %}">
                  Scholarship management System
                  {% if user.is_authenticated %}
                    {% if user.is_staff %}
                      <span class="icon-feather" data-toggle="tooltip" data-placement="right" title="Teacher profile"></span>
                    {% else %}
                      <span class="icon-graduation-cap" data-toggle="tooltip" data-placement="right" title="Student profile"></span>
                    {% endif %}
                  {% endif %}
                </a>
              </h1>
            </div>
            <div class="col-6 text-right">
              {% if user.is_authenticated %}
                <p class="pt-3">Logged in as <strong>{{ user.username }}</strong>. <a href="{% url 'logout' %}">Log out</a>.</p>
              {% else %}
                <a href="{% url 'login' %}" class="btn btn-light" role="button">Log in</a>
                <a href="{% url 'student_signup' %}" class="btn btn-primary" role="button">Sign up</a>
              {% endif %}
            </div>
          </div>
          <div class="card mb-3">
            <div class="card-body">
              {% for message in messages %}
                <div class="alert {{ message.tags }} alert-dismissible fade show" role="alert">
                  {{ message }}
                  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                  </button>
                </div>
              {% endfor %}
              {% block content %}
              {% endblock %}
            </div>
          </div>
          <footer>

            <a href="/">Home</a>
            /
            <a href="/teams/">SMS Team</a>
            /
            <a href="#">All Rights Reserved</a>
            
          </footer>
        </div>
      </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script type="text/javascript">
      $(function () {
        $('[data-toggle="tooltip"]').tooltip();
      })
    </script>
  </body>
</html>

templates/team.html
{% extends 'base.html' %}

{% block content %}
    <div class="teams">
        <ul>
            <li>Built by Ashish Thapa</li>
        </ul>
    </div>
{% endblock %}